### ISSUE TITLE
Add USERPROFILE for windows

### ISSUE THREAD

**Issue by ruslo** [hunter-packages/gate#3]
https://github.com/ruslo/hunter/issues/8

**Comment by ruslo** [comment]
@alamaison New version check `%SYSTEMDRIVE%/.hunter` directory. If environment not found - check `%USERPROFILE%/.hunter` directory.

**Comment by alamaison** [comment]
Is this the correct order to check them in?  I would have though `%USERPROFILE%/.hunter` should be preferred because this is writeable for all users.

`%SYSTEMDRIVE%/.hunter` is the Windows equivalent of `/.hunter` on Unix.

**Comment by ruslo** [comment]
> I would have though %USERPROFILE%/.hunter should be preferred because this is writeable for all users

There are problems with spaces for some packages so I was thinking that the probability of spaces appeared in `USERPROFILE` is not zero. Also `SYSTEMDRIVE` is shorter, which is good for windows limit of 256 symbols. It's always possible to set root by `HUNTER_ROOT` environment variable, is it enough?

**Comment by alamaison** [comment]
Ok, I understand your logic.  I'll give it some thought.  Perhaps there is a better way round these problems, because writing to `C:\` has been discouraged for decades.

**Comment by ruslo** [comment]
That's how it works for OpenSSL before (%WINDIR%): https://github.com/ruslo/hunter/blob/1077dc268b0a0062f7c2582b869934234c2ebcc0/cmake/schemes/url_sha1_openssl_windows.cmake.in because of space problems. Now this hack removed. So what do you think about writing to `USERPROFILE` if there are no spaces in path and to `SYSTEMDRIVE` otherwise?

**Comment by alamaison** [comment]
> what do you think about writing to USERPROFILE if there are no spaces in path and to SYSTEMDRIVE otherwise?

That becomes too complicated.  I prefer just SYSTEMDRIVE then.

The usual workaround in this situation is to use the 'short path' facility on Windows, otherwise known as 8.3 paths.  A legacy from DOS days, all paths with non-A-Z characters and more than 8.3 letters per segment are shorteded using a ~.  For example: `C:\Users\Alexander Lamaison` would become something like `C:\Users\Alexan~1`.  Unfortunately, I don't know how to make CMake produce shortened paths.

**Comment by ruslo** [comment]
> Unfortunately, I don't know how to make CMake produce shortened paths

CMake itself use [extended-path format `\\?\C:\`](https://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath), see [ConvertToWindowsExtendedPath](https://github.com/Kitware/CMake/blob/master/Source/kwsys/SystemTools.cxx#L1996). But problem is with the native tool (i.e. Visual Studio). Last time I've checked this problem I create simple MSVC project manually and copy it to directory with long path, when I've tried to open it I've got error "path too long", hence it can't be fixed in CMake as far as I understand. Anyway this can be fixed by [HUNTER_BINARY_DIR](https://github.com/ruslo/hunter/wiki/CMake-Variables-%28User%29#hunter_binary_dir-environment-variable) trick, so the main problem is spaces.
